inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Max: 80
  Exclude:
    - 'spec/**/*.rb'
    -
RSpec/ExampleLength:
  Max: 25

Layout/LineLength:
  Max: 250

RSpec/DescribedClass:
  Exclude:
    - 'spec/lib/hyrax/hirmeos/metrics_tracker_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/config/hyrax_events_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/lib/hyrax/hirmeos/metrics_tracker_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/jobs/hirmeos_work_updater_job_spec.rb'