inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'vendor/**/*'
    - 'spec/*'
Metrics/BlockLength:
  Max: 50
RSpec/ExampleLength:
  Max: 20
