inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Max: 80
RSpec/ExampleLength:
  Max: 25
Layout/LineLength:
  Max: 250

RSpec/DescribedClass:
  Exclude:
    - 'spec/lib/hyrax/hirmeos/metrics_tracker_spec.rb'
